# Generated by Django 3.2.16 on 2025-05-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20250502_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(default='', max_length=200, verbose_name='Комментарии'),
        ),
    ]
